config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :accounts, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :topics, :posts, :debates, :accounts, :comments
  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get, :post]
  match 'auth/failure', to: redirect('/') , :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout' , :via => [:get, :post]
  root "topics#index"
  match '/:controller(/:action(/:id))', :via => [:get, :post]

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :debates, :dependent => :destroy # Many debates can be created for a single topic if the topic is destroyed, then distroy the child debates 
	accepts_nested_attributes_for :debates, allow_destroy: true 

	has_one :debate_room
	has_one :story
	has_one :challenge
	belongs_to :account
	has_one :content, as: :content_owner
	scope :newest, lambda{select("MAX('created_at')")}
	scope :visible, lambda{where(visibility: 'visible')}
	scope :newest_first, lambda{order("topics.created_at DESC")}
	scope :search, lambda{|query|
		where(["topic_sentence LIKE ?", "%#{query}%"])}
	

	# topic submission validations
	# validates_presence_of :topic_sentence
	# validates_presence_of :account_id
	validates_presence_of :left_side_topic
	validates_length_of :left_side_topic, :within => 1..100
	# validates_presence_of :right_side_topic
	validates_length_of :topic_sentence, :within => 1..100
	# unwanted validation. Look again
	#validates_presence_of :description
	# returns the creator of this topic
	def get_creator
		return Account.find(self.account_id)
	end 

	#returns a list of debates under this topic in which a user is participating
	def get_user_involvment_number account_id
		count = 0
		self.debates.each do |debate|
			if debate.has_debater account_id
				count+=1
			end

		end
		return count

	end

	#returns a list of users on the given side of the topic
	def get_users_on_side side
		debates = []
		self.debates.each do |debate|
			puts debate.side_taken
			if debate.side_taken == side

				debates << debate
				debates
			end
		end 
		return debates
	end

	def self.sort_for_home_page
		sorted_topics = []
		all_topics = Topic.visible
		all_topics.each do |topic|
			if topic.has_finished_debate
				sorted_topics << topic
			end

		end
		all_topics.each do |topic|
			unless sorted_topics.include? topic
				sorted_topics << topic
			end
		end
		return sorted_topics
	end
	
	def is_involved account
		return true
	end

	def has_finished_debate
		self.debates.each do |debate|
			if debate.is_over 5
				return true
			end

		end
		return false
	end

	#thsi functions should be ad
	def is_open
		return (self.challenge.status == "open")&&(!self.has_email_challengee)&&(!self.has_account_challengee)
	end

	def is_full
		return self.debates.first.full?
	end

	def has_account_challengee
		return (self.challenge != nil) && (self.challenge.challengee_id != nil) 
	end

	def has_email_challengee
		return (self.challenge != nil) && (self.challenge.challengee_email != nil) 
	end

	def display_user_prompt_for account
		if !((self.is_full) || (self.get_creator == account))
			if(self.is_open)
				return true

			elsif((self.has_account_challengee && (self.challenge.challengee_id == account.id))&& !(self.challenge.status == "refused") )
				return true

			elsif(self.has_email_challengee && (self.challenge.challengee_email == account.email))
				return true
			end 
			return false
		else 
			return false
		end
		return false
	end

	def display_challenge_refused_for account
		if !self.is_open && !self.is_full
			if ((self.get_creator == account)&&(self.challenge.challenger_id == account.id))
				return self.challenge.status == "refused"
			else
				return false
			end
		else
			return false
		end

	end
	
	def get_challengee
		return Account.find(self.challenge.challengee_id)

	end

	def has_user_waiting account
		return ((self.challenge != nil)&&(self.challenge.challenger_id == account.id)&& !(self.is_full))
	end




end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	layout "main"
	before_action :authenticate_account!, :only => [:show]
	def index
		@topics = Topic.sort_for_home_page

	end

	def show		
		@topic = Topic.find(params[:id])
		
	end

	def edit

	end
	
	

	def update
		puts params.inspect
		@new_topic = Topic.find(params[:id])
		if @new_topic.update(topic_params)
	    	redirect_to(@new_topic)
	    else 
	    	redirect_to(:controller => "topics", :action => "index")
	    end 
	end 

	def new

	end
	
	# def create
	# 	if topic_params[:left_side_topic] == ""
	# 		topic_params[:left_side_topic] = "For"
	# 	end 
	# 	if topic_params[:right_side_topic] == ""
	# 		topic_params[:right_side_topic] = "Against" 
	# 	end
	# 		@topic = Topic.new(topic_params)

	# 	@topic.debates.build
	# 	if @topic.save
    #  			@topic
    #  			redirect_to(:action => 'show', :id => @topic.id)
    #  		else 
    #  			flash[:notice] = topic_params
    #  			redirect_to(:action => 'index')


    #   		end
	# end

	def og_create
		puts params
 		@topic = Topic.new(account_id: current_account.id, topic_sentence: params[:topic_sentence], description: params[:description], left_side_topic: params[:left_side_topic], right_side_topic: "")
 		

 		story = @topic.build_story
 		og = OpenGraph.new(params[:og_url])

 		story.og_topic =  og.title
 		story.og_type = og.type
 		story.og_description = og.description
 		story.og_image_url = og.images.first
 		story.og_url = params[:og_url]


		debate = @topic.debates.build
		if @topic.save
  			if story.save!
  			 	debate.register_participant current_account.id, "left"

  			 	if params[:opponent_email] != ""
  			 		Challenge.create!(:topic_id => @topic.id, :challenger_id => current_account.id, challengee_email: params[:opponent_email])
 					UserMailer.invitation_by_email(current_account, params[:opponent_email], Topic.find(@topic.id)).deliver
		 		elsif params[:selected_opponent_id] != "-1"
		 			Challenge.create!(:topic_id => @topic.id, :challenger_id => current_account.id, challengee_id: params[:selected_opponent_id])
 					UserMailer.invitation_by_email(current_account, Account.find(params[:selected_opponent_id]).email, Topic.find(@topic.id)).deliver
		 		else
		 			Challenge.create!(:topic_id => @topic.id, :challenger_id => current_account.id, status: "open")
 					
		 		end
		 			 			
			    respond_to do |format|
			 			@debate = debate
			 			@account = ""
			 			if params[:selected_opponent_id] == "-1"
			 				@account = "--no_account--"
			 			else
							@account =  Account.find(params[:selected_opponent_id])				
						end
						format.js {render "topics/og_create.js.erb", status: :ok}
				
					
				end
		 		
  				#j render(:partial => "topics/partials/rich_topic_index", :locals => {topic: @topic, debate: debate})
  			end  			
  		else 
  			#flash[:notice] = topic_params
  			redirect_to(:action => 'index')
  		end
	end

	
	def destroy
		@topic_to_delete = Topic.find(params[:id])
		if @topic_to_delete.destroy
			render json: @topic_to_delete
		else
			flash[:alert] = "couldn't delete topic"
			render json: {error: "couldn't perform action"}
		end
	end 
	
	private

		# def topic_params

		# 	params[:topic][:account_id] = current_account.id
			
		# 	params.require(:topic).permit(:account_id, :topic_sentence, :description, :left_side_topic, :right_side_topic)
		# end	
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/partials/_challenge_refused_box.html.erb
<div class = "debate-content" id = "prompt_join_box_<%= topic.id%>">
	<div class = "row">
		<div class = "col-md-12">
			<div class = "join_prompt_container">
				Your opponent has refused to take part in this conversation. What do you want to do?
				<div class = "small_devider"></div>
				<div class = "row">
					<div class = "col-md-12">
						<button id = "discard_conversation_<%= topic.id%>" class = "btn btn-toucan btn-sm pull-left">discard conversation </button>
						<button id = "challenge_somebody_else_<%= topic.id%>" class = "btn btn-toucan btn-sm pull-right">challenge somebody else </button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$("#challenge_somebody_else_<%= topic.id%>").click(function(){
	$("#invitation_modal_<%= topic.id%>").modal('show');
});
$("#discard_conversation_<%= topic.id%>").click(function(){
	$("#discard_conversation_modal_<%= topic.id%>").modal('show');
});
</script>

<%= render partial: "topics/partials/invitation_modal", locals: {topic: topic, debate: debate} %>
<%= render partial: "topics/partials/discard_conversation_modal", locals: {topic: topic, debate: debate} %>

app/views/topics/partials/_discard_conversation_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="discard_conversation_modal_<%= topic.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div style = "position: relative;" class="modal-dialog">
    <div style = "position: absolute; z-index: 1; width:100%;" class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">What do you want to do?</h4>
      </div>
      <div class="modal-body">
        <div class = "join_prompt_container">
        You don't necessarily need to discard this conversation. You can make it open instead so that any one interested can join you. 
        <div class = "small_devider"></div>
        <div class = "row">
          <div class = "col-md-12">
            <button id = "discard_conversation_<%= topic.id%>" class = "btn btn-toucan btn-sm pull-left">No, discard conversation </button>
            <button id = "make_it_open_<%= topic.id%>" class = "btn btn-toucan btn-sm pull-right">I'd like to make it open </button>
          </div>
        </div>
      </div>
      </div>
  </div>

</div>
</div>
<script type="text/javascript">
$("#discard_conversation_<%= topic.id%>").click(function(){
  var discard_conversation_<%= topic.id%> = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/discard_conversation", "POST", {topic_id: <%= topic.id%>} , display_ogp);
            discard_conversation_<%= topic.id%>.make_call();
});
 


</script>

app/views/topics/partials/_edit_topic_box.html.erb
<div class="stepwizard">
	<div class="stepwizard-row setup-panel">
		<div class="stepwizard-step">
			<a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
			<p>Title</p>
		</div>
		<div class="stepwizard-step">
			<a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
			<p>Sides</p>
		</div>
		<div class="stepwizard-step">
			<a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
			<p>Setup</p>
		</div>		
	</div>
</div>
<%= form_for(topic, :role => "form") do |f| %>
<div class="row setup-content" id="step-1">
	<div class="col-xs-12">
		<div class="col-md-12">
			<div class="form-group">
				<label class="control-label">Title</label>
				<%= f.text_field(:topic_sentence, maxlength: "100",  type: "text", required: "required", :class => "form-control")%>

			</div>
			<div class="form-group">
				<label class="control-label">Description</label>

				<%= f.text_area(:description, maxlength: "500",  type: "text", :class => "form-control")%>
			</div>
			<div class="modal-footer">       
				<div id = "users_modal_wait" style ="height: 30px;" class = "nextBtn topic_button topic_create_split_right col-xs-12 col-md-12">
					Next
				</div>

				<div style = "clear:both">
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row setup-content" id="step-2">
	<div class="col-xs-12">
		<div class="col-md-12">

			<div class="form-group">
				<label class="control-label">Company Name</label>
				<%= f.text_field(:left_side_topic, maxlength: "100",  type: "text", :class => "form-control")%>
			</div>
			<div class="form-group">
				<label class="control-label">Company Address</label>
				<%= f.text_field(:right_side_topic, maxlength: "100",  type: "text",  :class => "form-control")%>
			</div>
			<div class="modal-footer">       
				<div id = "users_modal_wait" style ="height: 30px;" class = "nextBtn topic_button topic_create_split_right col-xs-12 col-md-12">
					Next
				</div>

				<div style = "clear:both">
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row setup-content" id="step-3">
	<div class="col-xs-12">
		

			<div class="modal-footer">
				<div style ="height: 30px;" id = "reveal_description_button" class = "topic_button topic_create_split_left col-xs-12 col-md-6">
					Cancel
				</div>
				

					<%= f.submit("Submit", :style => "border: 0px solid transparent; background: transparent; height: 30px;", :class => "topic_button topic_create_split_right col-xs-12 col-md-6" )%>


				<div style = "clear:both">
				</div>
			</div>

		
	</div>
</div>
<% end %>

app/views/topics/partials/_invitation_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="invitation_modal_<%= topic.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div style = "position: relative;" class="modal-dialog">
    <div style = "position: absolute; z-index: 1; width:100%;" class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Friends</h4>
      </div>
      <div class="modal-body">
        <ul>
          <%Account.all.each do |user|%>
          <% unless user == current_account%>
          <li class = "invitable_user_<%= topic.id%>" invitable-user-id = <%= user.id%>>
            <%= render(:partial => "topics/partials/user_bar", :locals => {:user => user})%>
          </li>
          
          <div class = "small_devider"></div>
          <% end%>
          <%end%>
          <div style = "clear:both"></div>
        </ul>
        <div class = "small_devider"></div>
        <div class = "small_devider"></div>
        Couldn't find who you were looking for? Send an email invitation
         <input id = "invitation_email_box_<%= topic.id%>" type = "text" class = "form-control" , placeholder = "email">
         <div class = "message_box" id = "invitation_email_message_box_<%= topic.id%>">
               </div>
     <div class="modal-footer">
        <div data-toggle="modal" style ="height: 30px;" id = "send_invitation_button_<%= topic.id%>" class = "topic_button col-xs-12 col-md-12">
        Send Invitation
        </div>
        
       
        <div style = "clear:both">
        </div>
      </div>
    </div>
  </div>
<div style = " 
                text-align: center;
                color: red;
                padding-top: 100px;
                position: absolute;
                height: 319px;
                width: 100%;
                border-radius: 10px;
                background-color: rgb(255,255,255);
                z-index: 1005;
                opacity: 0.7;" 
                class = "hidden progress-div"
                id = "prog_mod_div_<%= topic.id%>">
        <i class="fa fa-spinner fa-spin fa-3x fa-fw margin-bottom"></i>
        <div>
          Sending ...
        </div>

</div>
</div>
</div>
<script type="text/javascript">

 prepare_invitable_user_list_<%= topic.id%> = function(){
  t = new Array();
  j_list = $(".invitable_user_<%= topic.id%>");
  j_list.each(function(element){
    t[element] = j_list[element];
  });
  return t;
}



get_selected_invitable_user_id_<%= topic.id%> = function(){
  id = -1;
  prepare_invitable_user_list_<%= topic.id%>().forEach(function(element){
    if ($(element).attr("picked") == "true"){
      //console.log(element);
      id = $(element).attr("invitable-user-id");
    }
    
  });
  return id;
}

after_invitation_callback_<%= topic.id%> = function(element){
  // $("#join_form_<%= topic.id%>").empty();
  $("#prog_mod_div_<%= topic.id%>").addClass("hidden");
  $("#invitation_modal_<%= topic.id%>").modal('hide'); 
}
  
var radio_form_for_invitable_users_<%= topic.id%> = new RadioList(prepare_invitable_user_list_<%= topic.id%>(), "glyphicon-check", "glyphicon-unchecked");

  var validator = new StringValidator()

  $("#send_invitation_button_<%= topic.id%>").click(function(){
    curtain_height = $("#invitation_modal_<%= topic.id%>").find(".modal-content").height();
    $("#prog_mod_div_<%= topic.id%>").css({height: curtain_height});
    $("#prog_mod_div_<%= topic.id%>").removeClass("hidden");
    var validator = new StringValidator()
    if ($("#invitation_email_box_<%= topic.id%>").val() != ""){
       if(validator.is_valid_email($("#invitation_email_box_<%= topic.id%>").val())){
           var invitation_handler = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/send_email_invitation", "POST", {reciever_email: $("#invitation_email_box_<%= topic.id%>").val(), side: get_picked_side(), topic_id: <%=topic.id%>} ,after_invitation_callback);
              invitation_handler.make_call();
       }
       else
       {
         $("#invitation_email_message_box_<%= topic.id%>").text("Please enter a valid email")
       }
    }
    else 
    {
      var selected_invitation_handler_<%= topic.id%> = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/send_invitation", "POST", {challengee_id: get_selected_invitable_user_id_<%= topic.id%>(), topic_id: <%=topic.id%>} ,after_invitation_callback_<%= topic.id%>);
              selected_invitation_handler_<%= topic.id%>.make_call();
    }
  });


</script>

app/views/topics/partials/_join_box.html.erb
<!-- takes in user, topic and as an input -->
<div class = "debate-content" >
    <div class = "row">
        <div class = "col-md-12">
            <div class = "join_prompt_container">
                <% if ((topic.is_open) && !(debate.has_debater user.id)) %>
                <textarea id = "open_topic_side_input_<%=topic.id%>" style = "border-radius: 2px;" class = "form-control" rows = "1" placeholer = "state your side and join ..."> </textarea>
                <div  class = "small_devider"></div>
                <button id = "open_topic_join_btn_<%= topic.id%>" class = "btn btn-sm btn-toucan pull-right">join</button>
                <script type="text/javascript">
                 joining_icon_box_<%= topic.id%> = function(){                            
                    $("#join_form_<%= topic.id%>").addClass("hidden");
                    $("#joining_box_<%= topic.id%>").removeClass("hidden");
                    $("#join_form_<%= topic.id%>").remove();
                }
                update_rich_topic_<%= topic.id%> = function(data){
                    $("#joining_box_<%= topic.id%>").addClass("hidden");
                    $("#one_side_topic_<%= topic.id%>").remove();

                    $("#sides_container_<%= topic.id%>").append(data);


                }
                $("#open_topic_join_btn_<%= topic.id%>").click(function(){

                    right_input = $("#challenge_topic_side_input_<%= topic.id%>").val();
                    joining_icon_box_<%= topic.id%>();
                    var join_ajax_<%= topic.id%> = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/join_debate_from_rich_index", "POST", {debate_id: <%=debate.id%>, right_side_topic: $("#open_topic_side_input_<%=topic.id%>").val(), topic_id: <%=topic.id%>} ,update_rich_topic_<%= topic.id%>);
                    join_ajax_<%= topic.id%>.make_call();

                });

                </script>
                <% elsif  (((topic.has_account_challengee)&&(topic.challenge.get_challengee == user))||((topic.has_email_challengee)&&(topic.challenge.challengee_email == user.email))) %>
                <span style = "font-size: smaller;"><strong>state your view and join</strong></span>
                <textarea id = "challenge_topic_side_input_<%= topic.id%>" style = "border-radius: 2px;" class = "form-control" rows = "1" placeholer = "state your side and join ..."> </textarea>
                <div  class = "small_devider"> </div>
                <button id = "challenge_topic_join_btn_<%= topic.id%>" class = "btn btn-sm btn-toucan pull-right" >join</button>
                <script type="text/javascript">
                joining_icon_box_<%= topic.id%> = function(){                            
                    $("#join_form_<%= topic.id%>").addClass("hidden");
                    $("#joining_box_<%= topic.id%>").removeClass("hidden");
                    $("#join_form_<%= topic.id%>").remove();
                }
                update_rich_topic_<%= topic.id%> = function(data){
                    $("#joining_box_<%= topic.id%>").addClass("hidden");
                    $("#one_side_topic_<%= topic.id%>").remove();

                    $("#sides_container_<%= topic.id%>").append(data);


                }
                $("#challenge_topic_join_btn_<%= topic.id%>").click(function(){
                    right_input = $("#challenge_topic_side_input_<%= topic.id%>").val();
                    joining_icon_box_<%= topic.id%>();
                    var join_ajax_<%= topic.id%> = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/join_debate_from_rich_index", "POST", {debate_id: <%=debate.id%>, right_side_topic: right_input, topic_id: <%=topic.id%>} ,update_rich_topic_<%= topic.id%>);
                    join_ajax_<%= topic.id%>.make_call();

                });

                </script>
                <% else %>

                <% end%>
            <div style = "clear:both">
            </div>
            </div>
        </div>
    </div>
</div>

app/views/topics/partials/_profile_box.html.erb
<div class = "profile_box_outer_container">
	<div class = "profile_pic_container"
	<%= image_tag("koala.jpg", size: "100x100")%>
</div>

app/views/topics/partials/_rich_topic_index.html.erb
<div id = "topic_index_pannel_<%= topic.id %>" topic-id = <%= topic.id %> class="topic_index_pannel panel panel-default panel-main">
    <!-- a dropdown menu of currently unknown purpose -->
    <div class="topic_index_dropdown dropdown">
        <span class="dropdown-toggle" type="button" data-toggle="dropdown">
            <span class="[ glyphicon glyphicon-chevron-down ]"></span>
        </span>
        <ul class="dropdown-menu" role="menu">
            <li class = "topic_index_dropdown_topic_edit" role="presentation"><a role="menuitem" tabindex="-1"><span class = " glyphicon glyphicon-pencil"> </span>  Edit</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><span class ="glyphicon glyphicon-lock"></span>  Only you and friends</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"> Another action</a></li>
            <li role="presentation" class="divider"></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#"><span class ="glyphicon glyphicon-trash"></span> Another action</a></li>
        </ul>
    </div>

    <!-- stuff like topic, post info, user info and content (panel-heading is a misnomer) -->
   
    <div class="panel-heading">
        <div class = "small_devider"></div>

        <div class ="debate-title">
            <div class = "row">
            <div class = "col-md-12">
                <div class = "post-box-profile-img-container">
                    <%= image_tag("default.png", :alt => "+", :class => "profile-pic-container")%>

                </div>
                <div class = "post-box-profile-info-container">
                    <div class = "post-box-profile-info">
                        <span class = "profile-info-name"><%= topic.get_creator.display_name%></span>
                        <span class = "profile-info-meta">a few seconds ago</span><!-- create and use a friendly time stamp here -->
                    </div>
                    <div class = "profile-info-description info_text" style = "padding: 4px;">

                    </div>
                </div>
            </div>
        </div>
        <% if request.env['PATH_INFO'] == topic_path(topic) %>
            <% if !topic.is_full %>
            <p><%= topic.topic_sentence%></p>
            <% else %>
            <p><%= link_to topic.topic_sentence, debate_path(debate)%> </p>
            <% end %>  
        <%else%>
           
            <p><%= link_to topic.topic_sentence, topic_path(topic)%> </p>
           
        <% end%>  
            <hr>
        </div>
        <div class="debate-content text-description">
            <div id = "sides_container_<%= topic.id%>">
            <% if topic.is_full %>
                <%= render partial: "topics/partials/sides_and_status", locals: {topic: topic, debate: debate} %>
            <% elsif !topic.is_full %>
                
            <div id = "one_side_topic_<%= topic.id%>"> <!-- takes in a hash object, name: ogp_object -->
                <p><%=topic.left_side_topic%></p>
            </div>
            
            <% end %>
            </div>

        </div>
        
        <% unless topic.story.og_image_url == nil %>
        <div class="debate-content text-description">
            <p> <!-- takes in a hash object, name: ogp_object -->

                <div class = "ogp_image">
                    
                        <%= image_tag(topic.story.og_image_url, :width => "100%")%>
                    
                    
                </div>

                <div class  = "ogp_title">
                    <h3 onclick = "window.open('<%= topic.story.og_url%>')"> <%= topic.story.og_topic%> </h3>
                    <p>
                        <%= topic.story.og_description%>
                    </p>
                </div>
                       
            </p>


        </div>
        <% end %>
         <% if topic.is_full%>
            <%= link_to "to spar arena", debate_path(topic.debates.first), class: "go_to_story_btn btn btn-default btn-sm pull-right"%>
       
        <% end %>
    </div>

    <!-- stuff like debaters and their positions -->
    <div  class = "small_devider"></div>
    <div class = "panel-body">
       <div class = "row" >
            <div id = "joining_box_<%= topic.id%>" class = "col-md-12 hidden">
                <div style = "padding-left: 45%; color: red;">
                    <i class="fa fa-spinner fa-spin fa-3x fa-fw margin-bottom"></i>
                    <div>
                        <strong>joining ...</strong>
                    </div>
                </div>
            </div>

            <div class = "col-md-12" id = "join_form_<%= topic.id%>">
                <% if (account_signed_in?) && (topic.display_user_prompt_for current_account) %>

                <%=render partial: "topics/partials/prompt_join_box", locals: {user: current_account, topic: topic, debate: debate}%>

                <% elsif (account_signed_in?) && (topic.display_challenge_refused_for current_account)%>
                <%=render partial: "topics/partials/challenge_refused_box", locals: {user: current_account, topic: topic, debate: debate}%>
                <% end%>
            </div>
        </div>

    </div>
    <!-- stuff like social box  -->
    <hr class = "default-separator">
    <div class = "panel-footer">
        <div class = "social-box text-social">
            <div class = "col-md-8" style ="height: 30px;">
                Upvote<span class ="social-box-stat">43+</span>&nbsp;&nbsp;    Downvote  &nbsp;&nbsp;&nbsp;    Share <span class ="social-box-stat">43+</span>
            </div>
            <div class = "col-md-4 social-box-right">
                Stats 
            </div>
            
            <div style = "clear:both"></div>
        </div>
    </div>                      
</div>

<script type="text/javascript">

    <% if current_account == topic.get_creator %>

    $(".topic_index_dropdown_topic_edit").click(function(){

        $("#edit_topic_modal").modal('show');  
    }); 


    <% end %>
  



</script>

<!-- Modal -->
<div class="modal fade" id="edit_topic_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style = "border-bottom: none;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <%= render partial: "topics/partials/edit_topic_box", :locals => {:topic => topic}%>

        </div>
    </div>
</div>

app/views/topics/partials/_waiting_for_response.html.erb
<div class = "debate-content" id = "prompt_join_box_<%= topic.id%>">
	<div class = "row">
		<div class = "col-md-12">
			<div class = "join_prompt_container">
				waiting for <strong><%= topic.get_challengee.display_name%></strong> to respond.
				<div class = "small_devider"></div>
				
			</div>
		</div>
	</div>
</div>