config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :accounts, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :topics, :posts, :debates, :accounts, :comments
  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get, :post]
  match 'auth/failure', to: redirect('/') , :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout' , :via => [:get, :post]
  root "topics#index"
  match '/:controller(/:action(/:id))', :via => [:get, :post]

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :debates, :dependent => :destroy # Many debates can be created for a single topic if the topic is destroyed, then distroy the child debates 
	accepts_nested_attributes_for :debates, allow_destroy: true 

	has_one :debate_room
	has_one :story
	has_one :challenge
	belongs_to :account
	has_one :content, as: :content_owner
	scope :newest, lambda{select("MAX('created_at')")}
	scope :visible, lambda{where(visibility: 'visible')}
	scope :newest_first, lambda{order("topics.created_at DESC")}
	scope :search, lambda{|query|
		where(["topic_sentence LIKE ?", "%#{query}%"])}
	

	# topic submission validations
	# validates_presence_of :topic_sentence
	# validates_presence_of :account_id
	validates_presence_of :left_side_topic
	validates_length_of :left_side_topic, :within => 1..100
	# validates_presence_of :right_side_topic
	validates_length_of :topic_sentence, :within => 1..100
	# unwanted validation. Look again
	#validates_presence_of :description
	# returns the creator of this topic
	def get_creator
		return Account.find(self.account_id)
	end 

	#returns a list of debates under this topic in which a user is participating
	def get_user_involvment_number account_id
		count = 0
		self.debates.each do |debate|
			if debate.has_debater account_id
				count+=1
			end

		end
		return count

	end

	#returns a list of users on the given side of the topic
	def get_users_on_side side
		debates = []
		self.debates.each do |debate|
			puts debate.side_taken
			if debate.side_taken == side

				debates << debate
				debates
			end
		end 
		return debates
	end

	def self.sort_for_home_page
		sorted_topics = []
		all_topics = Topic.visible
		all_topics.each do |topic|
			if topic.has_finished_debate
				sorted_topics << topic
			end

		end
		all_topics.each do |topic|
			unless sorted_topics.include? topic
				sorted_topics << topic
			end
		end
		return sorted_topics
	end
	
	def is_involved account
		return true
	end

	def has_finished_debate
		self.debates.each do |debate|
			if debate.is_over 5
				return true
			end

		end
		return false
	end

	#thsi functions should be ad
	def is_open
		return (self.challenge.status == "open")&&(!self.has_email_challengee)&&(!self.has_account_challengee)
	end

	def is_full
		return self.debates.first.full?
	end

	def has_account_challengee
		return (self.challenge != nil) && (self.challenge.challengee_id != nil) 
	end

	def has_email_challengee
		return (self.challenge != nil) && (self.challenge.challengee_email != nil) 
	end

	def display_user_prompt_for account
		if !((self.is_full) || (self.get_creator == account))
			if(self.is_open)
				return true

			elsif((self.has_account_challengee && (self.challenge.challengee_id == account.id))&& !(self.challenge.status == "refused") )
				return true

			elsif(self.has_email_challengee && (self.challenge.challengee_email == account.email))
				return true
			end 
			return false
		else 
			return false
		end
		return false
	end

	def display_challenge_refused_for account
		if !self.is_open && !self.is_full
			if ((self.get_creator == account)&&(self.challenge.challenger_id == account.id))
				return self.challenge.status == "refused"
			else
				return false
			end
		else
			return false
		end

	end
	
	def get_challengee
		return Account.find(self.challenge.challengee_id)

	end

	def has_user_waiting account
		return ((self.challenge != nil)&&(self.challenge.challenger_id == account.id)&& !(self.is_full))
	end




end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	layout "main"
	before_action :authenticate_account!, :only => [:show]
	def index
		@topics = Topic.sort_for_home_page

	end

	def show		
		@topic = Topic.find(params[:id])
		
	end

	def edit

	end
	
	

	def update
		puts params.inspect
		@new_topic = Topic.find(params[:id])
		if @new_topic.update(topic_params)
	    	redirect_to(@new_topic)
	    else 
	    	redirect_to(:controller => "topics", :action => "index")
	    end 
	end 

	def new

	end
	
	# def create
	# 	if topic_params[:left_side_topic] == ""
	# 		topic_params[:left_side_topic] = "For"
	# 	end 
	# 	if topic_params[:right_side_topic] == ""
	# 		topic_params[:right_side_topic] = "Against" 
	# 	end
	# 		@topic = Topic.new(topic_params)

	# 	@topic.debates.build
	# 	if @topic.save
    #  			@topic
    #  			redirect_to(:action => 'show', :id => @topic.id)
    #  		else 
    #  			flash[:notice] = topic_params
    #  			redirect_to(:action => 'index')


    #   		end
	# end

	def og_create
		puts params
 		@topic = Topic.new(account_id: current_account.id, topic_sentence: params[:topic_sentence], description: params[:description], left_side_topic: params[:left_side_topic], right_side_topic: "")
 		

 		story = @topic.build_story
 		og = OpenGraph.new(params[:og_url])

 		story.og_topic =  og.title
 		story.og_type = og.type
 		story.og_description = og.description
 		story.og_image_url = og.images.first
 		story.og_url = params[:og_url]


		debate = @topic.debates.build
		if @topic.save
  			if story.save!
  			 	debate.register_participant current_account.id, "left"

  			 	if params[:opponent_email] != ""
  			 		Challenge.create!(:topic_id => @topic.id, :challenger_id => current_account.id, challengee_email: params[:opponent_email])
 					UserMailer.invitation_by_email(current_account, params[:opponent_email], Topic.find(@topic.id)).deliver
		 		elsif params[:selected_opponent_id] != "-1"
		 			Challenge.create!(:topic_id => @topic.id, :challenger_id => current_account.id, challengee_id: params[:selected_opponent_id])
 					UserMailer.invitation_by_email(current_account, Account.find(params[:selected_opponent_id]).email, Topic.find(@topic.id)).deliver
		 		else
		 			Challenge.create!(:topic_id => @topic.id, :challenger_id => current_account.id, status: "open")
 					
		 		end
		 			 			
			    respond_to do |format|
			 			@debate = debate
			 			@account = ""
			 			if params[:selected_opponent_id] == "-1"
			 				@account = "--no_account--"
			 			else
							@account =  Account.find(params[:selected_opponent_id])				
						end
						format.js {render "topics/og_create.js.erb", status: :ok}
				
					
				end
		 		
  				#j render(:partial => "topics/partials/rich_topic_index", :locals => {topic: @topic, debate: debate})
  			end  			
  		else 
  			#flash[:notice] = topic_params
  			redirect_to(:action => 'index')
  		end
	end

	
	def destroy
		@topic_to_delete = Topic.find(params[:id])
		if @topic_to_delete.destroy
			render json: @topic_to_delete
		else
			flash[:alert] = "couldn't delete topic"
			render json: {error: "couldn't perform action"}
		end
	end 
	
	private

		# def topic_params

		# 	params[:topic][:account_id] = current_account.id
			
		# 	params.require(:topic).permit(:account_id, :topic_sentence, :description, :left_side_topic, :right_side_topic)
		# end	
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/create.js.erb
<% publish_to "/topics/main" do %>
	
	$("#topic_creater_box_outer_container").after("<%= j render(:partial => 'topics/partials/topic_index', :locals => {:topic => @topic}) %>");
<% end %>
     

app/views/topics/index.html.erb
<div class="container">
    <div class="row">

        <!-- left navigation pane -->
        
        <div class = "col-md-2 col-xs-12">   
           
        </div>

        <!-- main content area -->
        <div  class = " col-md-6">
            <ul id = "main-content-container">
                <% if account_signed_in?%>
                <li id = "topic_creator_container">
                   <%= render(:partial => "topics/partials/topic_box_place_holder") %>
                </li>
                <% end %>
               <!--  <li>
                    <div class = "row">
                        <div class = "col-md-12">
                        </div>
                    </div>
                </li> -->

                <% @topics.each do |topic|%>
                <li>
                    <% if topic.story != nil%>
                    <%= render(:partial => "topics/partials/rich_topic_index", :locals => {:topic => topic, :debate => topic.debates.first}) %>
                    <% else %>
                    <%= render(:partial => "topics/partials/topic_index", :locals => {:topic => topic}) %>
                    <% end %>
                </li>
                <%end%> 
            </ul>
        </div>
        <!-- right navigation pane -->
        <div class = "col-md-4">

        </div>  
    </div>
</div>
<script type="text/javascript">
<% if alert != nil %>
notification_under_nav.notify_under_nav(1000, 1000000, "<%= alert%>");
<% end %>
</script>
<%= subscribe_to "/topics/main" %>

app/views/topics/join_debate.js.erb
<% publish_to "/topics/main" do %>
	$("#sides_container_<%= @topic.id%>").empty();
	$("#sides_container_<%= @topic.id%>").append('<%= j render(:partial => "topics/partials/sides_and_status", locals: {:topic => @topic, :debate => @debate})%>');
	$("#topic_index_pannel_<%= @topic.id %>").click(function(){

        window.location.href = "<%= debate_url @debate%>";

    });
<% end %>
     

app/views/topics/og_create.js.erb
<% publish_to "/topics/main" do %>
	$("#topic_creator_container").after('<%= j render(:partial => "topics/partials/rich_topic_index", :locals => {topic: @topic, debate: @debate})%>');
<% end %>
<% publish_to account_path(@account) do %>
<% unless @account == "--no_account--"%>
console.log(<%= @account.id%>)
    $("#join_form_<%= @topic.id%>").append('<%= j render(:partial => "topics/partials/prompt_join_box", :locals => {user: @account, topic: @topic, debate: @debate})%>');
<% end %> 
<% end %>    

app/views/topics/one_debater.js.erb
<% publish_to @path do %>
	$("[debate-id = <%= @debate.id%>]").remove();
	$("#sides_container").after("<%= j render(:partial => 'topics/partials/one_user_temp', :locals => {:debate => @debate}) %>");
	if(current_user_id() != "<%=@debate.get_debaters.first.id%>")
	{
		console.log("temp_one_user_container_<%= @debate.id%>");
		console.log($("#temp_one_user_container_<%= @debate.id%>"));
		$("#temp_one_user_container_<%= @debate.id%>").removeClass("hidden");
		$("#join_opposite_side_button_<%= @debate.id%>").click(send_to_backend);
	}

<% end %>
     

app/views/topics/send_invitation.js.erb
<% publish_to account_path(@account) do %>
    console.log("rendered");
	$("#join_form_<%= @topic.id%>").append('<%= j render(:partial => "topics/partials/prompt_join_box", :locals => {user: @account, topic: @topic, debate: @topic.debates.first})%>');
<% end %>    

app/views/topics/show.html.erb
<div class="container">

    <div class="row">

        <!-- left navigation pane -->
        
       <div class = "col-md-3 col-xs-12">          

        </div>


        <!-- main content area -->
         <div id = "main_topic_show" topic-id = "<%= @topic.id %>" class = "col-xs-12 col-md-6" style ="margin-top: 10px;">
            <ul>
                <li>
                   <%= render(:partial => "topics/partials/rich_topic_index", :locals => {:topic => @topic, :debate => @topic.debates.first}) %>
                </li>
                
            </ul>
         </div>


    <!-- right navigation pane -->

    <div class = "col-md-3">

    </div>  

</div>
</div>
<%= subscribe_to topic_path(@topic) %>
<script type="text/javascript">
    get_topic_id = function(){
        return $("#main_topic_show").attr("topic-id");
    }




</script>

app/views/topics/two_debaters.js.erb
<% publish_to @path do %>
	$("[debate-id = <%= @debate.id%>]").remove()
	$("#sides_container").after("<%= j render(:partial => 'topics/partials/two_users', :locals => {:debate => @debate}) %>");
<% end %>
     