config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :accounts, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :topics, :posts, :debates, :accounts, :comments
  match 'auth/:provider/callback', to: 'sessions#create', :via => [:get, :post]
  match 'auth/failure', to: redirect('/') , :via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout' , :via => [:get, :post]
  root "topics#index"
  match '/:controller(/:action(/:id))', :via => [:get, :post]

end

app/views/admin/_side_bar.html.erb
 <nav class="nav-sidebar">
      <ul class="nav">
       
        <li class = "active"><%= link_to("Home", {:action => 'index'})%></li>
        <li><%= link_to("Debates", {:action => 'debates'})%></li>
        <li><%= link_to("Invitations", {:action => 'stats'})%></li>
        <% if current_account.privilege == 'super'%>
		<li role="presentation"><%= link_to("Reports", {:action => 'reports'})%></li>
		<li role="presentation"><a>Admins</a></li>
		<%end%>
        <li class="nav-divider"></li>
        <li><a href="javascript:;"><i class="glyphicon glyphicon-off"></i> Sign in</a></li>
      </ul>
    </nav>

app/views/admin/accounts.html.erb
<div class = "admin_index_main">
<div class = "container">
<div class = "row"> 
	<div class = 'col-lg-2'>
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><%= link_to("Home", {:action => 'index'},)%></li>
			<li role="presentation"><%= link_to("Debates", {:action => 'debates'},)%></li>
			<li role="presentation" class="active"><%= link_to("Accounts", {:action => 'accounts'},)%></li>
			<li role="presentation"><%= link_to("Stats", {:action => 'stats'},)%></li>
			<% if current_account.privilege == 'super'%>
        <li role="presentation"><%= link_to("Reports", {:action => 'reports'})%></li>
        <li role="presentation"><a>Admins</a></li>
      <%end%>
  		</ul>

	</div>

	<div class = 'col-lg-10'>
		<div class = "row">
			<div class = "col-lg-12"></div>
			<div class = "admin_main_content col-lg-12">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Id</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Display Name</th>
						<th>Privilege</th>
						<th>Set Tester</th>
						<th>Debates Created</th>
						<th>Delete</th>

					</tr>
				</thead>
				<tbody>
					<% Account.all.each do |user|%>
						<tr>
							<th scope="row"><%= user.id%></th>
							<td><%= link_to(user.first_name,:controller => 'topics', :action =>'test'  )%></td>
							<td><%= user.last_name%></td>
							<td><%= user.display_name%></td>
							<td><%= user.privilege%></td>
							<%unless user.is_tester%>

							<th><a class = "make_tester" user-id = <%= user.id%>>make tester</a></th>
							<%else%>
							<th>tester</th>
							<%end%>
							<td><%= user.topics.count%></td>
							
							<td><%= link_to("Delete", :controller => 'accounts', :action =>'destroy', :id => user.id)%></td>
							
						</tr>
						<%end%>
				</tbody>
			</table>
			</div>

		</div>
	</div>
</div>
</div>
</div>
<script type="text/javascript">
change_privilege = function(element, change_to){
	$(element).text("");
	$(element).text(change_to);
}
cal_bak = function(){}
$(".make_tester").click(function(){
	var ah = new AjaxHandler("join_modal", "<%= root_url%>"+"ajax_calls/make_tester","POST", {account_id: $(this).attr("user-id")}, cal_bak);//use rails way to find the url
        ah.make_call();
});
</script>

app/views/admin/debate_summary.html.erb
<div class="container">
 <div id="blog" class="row"> 

  <div class="col-sm-2 col-md-2 paddingTop20">
   <%= render partial: "admin/side_bar"%>
    <div><h2 class="add"></h2></div>
  </div>
  <div class="col-md-10 blogShort">
  <h3><%= @debate.get_topic.topic_sentence%></h3>
  <h4>
    <%=  @debate.get_left_debater == nil ? "None": @debate.get_left_debater.email %>
  </h4>
       &nbsp;&nbsp;
       VS
       &nbsp;&nbsp;
  <h4>   
       <%=  @debate.get_right_debater == nil ? "None": @debate.get_right_debater.email %>
       
  </h4>
  <br>
  <% @debate.posts.each do |post|%>
    <article>
      <strong>posted by: </strong><%= post.get_user.email%>
      <br>
      <strong>posted on: </strong> <%= post.created_at%>
      <br>
      <strong>edited on: </strong> <%= post.updated_at%>
      <br>
      <br>
      <p>
         <%= post.content.content_body%>
      </p>
    </article>
    <hr>
  <% end %>
  </div>


 <div class="col-md-12 gap10"></div>
</div>
</div>

app/views/admin/debates.html.erb
<div class="container">
 <div id="blog" class="row"> 

  <div class="col-sm-2 paddingTop20">
   <%= render partial: "admin/side_bar"%>
    <div><h2 class="add"></h2></div>
  </div>
  <div class="col-md-10 blogShort">
<ul>
    
    

   
   		<div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">Challenges</div>

     	<div class = "panel-body shell_simulator">
     	<% Log.all.each do |log|%>
     		<p>
     			<span  class = "info_text"><%= log.created_at%></span>
     			<br>
     			<span  class = "info_text"><%= Account.find(log.current_user_id).email%></span>
     			<%= log.event_log%>
     			<br>
     			<%= log.param%>
     			<br>
     			<span  class = "info_text">---------------------------------------------------------------------------</span>
     			
     			
     		</p>
     		<%end%>
     	</div>
	      
	    </div>
	  </div>
    
</ul>
  </div>

 <div class="col-md-12 gap10"></div>
</div>
</div>

app/views/admin/index.html.erb
<div class="container">
 <div id="blog" class="row"> 

  <div class="col-sm-2 col-md-2 paddingTop20">
   <%= render partial: "admin/side_bar"%>
   <div><h2 class="add"></h2></div>
 </div>
 <div class = "col-md-10">
  <ul>
    

    <% Topic.all.each do |topic|%>
    <li id = "admin_topic_box_<%= topic.id%>">
      <div class = "row">
        <div class = "col-md-9" >
           <% if topic.story != nil%>
                    <%= render(:partial => "topics/partials/rich_topic_index", :locals => {:topic => topic, :debate => topic.debates.first}) %>
                    <% else %>
                    <%= render(:partial => "topics/partials/topic_index", :locals => {:topic => topic}) %>
                    <% end %>
        </div>
        <div class = "col-md-3">
           <%= link_to action: "topic_debates", id: topic.id do %>
            <span class = 'btn btn-primary btn-sm', style = "width: 80px;"> 
            <i class="fa fa-cog"></i> Debates 
            </span>
           <% end %>
           <div class = "small_devider"></div>
            <%= link_to topic_path(topic), method: :delete, remote: true , :class => 'btn btn-danger btn-sm', :style => "width: 80px;", :id => "admin_topic_delete_#{topic.id}"  do %>
            <i class="fa fa-trash-o fa-sm"></i> Delete </a>
           <% end %>

          <div class = "small_devider"></div>
          <% if topic.visibility == "visible" %>
           <button id = "hide_topic_btn_<%= topic.id%>" class = 'btn btn-primary btn-sm', style = "width: 80px;"> 
            <i id = "hidden_fa_<%= topic.id%>" class="fa fa-eye-slash"> </i> 
           </button>
           <% else %>
           <button id = "set_visible_btn_<%= topic.id%>" class = 'btn btn-primary btn-sm', style = "width: 80px;"> 
            <i id = "hidden_fa_<%= topic.id%>" class="fa fa-eye"></i> <!--  <span id = "hide_lable_<%= topic.id%>">show</span> -->
           </button>
           <%end%>
           
        </div>
      </div>
    </li>
    <script type="text/javascript">
      change_hide_to_show_<%= topic.id%> = function(data){
        $("#hidden_fa_<%= topic.id%>").removeClass("fa-eye-slash");
        $("#hidden_fa_<%= topic.id%>").addClass("fa-eye");
        $("#hide_lable_<%= topic.id%>").val("hey work");
       
      }
      $("#hide_topic_btn_<%= topic.id%>").click(function(){
        
         var hide_topic_<%= topic.id%> = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/hide_topic", "POST", {topic_id: <%= topic.id%>} , change_hide_to_show_<%= topic.id%>);
                hide_topic_<%= topic.id%>.make_call();
      });
      change_show_to_hide_<%= topic.id%> = function(data){
        $("#hidden_fa_<%= topic.id%>").removeClass("fa-eye");
        $("#hidden_fa_<%= topic.id%>").addClass("fa-eye-slash");
        $("#hidden_fa_<%= topic.id%>").val("show");
        
      }
      $("#set_visible_btn_<%= topic.id%>").click(function(){
        
         var show_topic_<%= topic.id%> = new AjaxHandler("none", "<%= root_url%>"+"ajax_calls/show_topic", "POST", {topic_id: <%= topic.id%>} , change_show_to_hide_<%= topic.id%>);
                show_topic_<%= topic.id%>.make_call();
      });
      $("#admin_topic_delete_<%= topic.id%>").click(function(){
        $("#admin_topic_box_<%= topic.id %>").remove();
      });
    </script>
    <%end%> 
  </ul>
</div>


<div class="col-md-12 gap10"></div>
</div>
</div>

app/views/admin/reports.html.erb
<div class = "admin_index_main">
<div class = "container">
<div class = "row"> 
	<div class = 'col-lg-2'>
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><%= link_to("Home", {:action => 'index'},)%></li>
			<li role="presentation"><%= link_to("Debates", {:action => 'debates'},)%></li>
			<li role="presentation" ><%= link_to("Accounts", {:action => 'accounts'},)%></li>
			
			<li role="presentation"><%= link_to("Stats", {:action => 'stats'},)%></li>
			<% if current_account.privilege == 'super'%>
        <li role="presentation" class="active"><%= link_to("Reports", {:action => 'reports'})%></li>
        <li role="presentation"><a>Admins</a></li>
      <%end%>
  		</ul>

	</div>

	<div class = 'col-lg-10'>
		<div class = "row">
			<div class = "col-lg-12"></div>
			<div style = "font-family: 'monospace'; color: red; "class = "admin_main_content col-lg-12">
			<%@reports.each do |report|%>
			<div class = "small_devider"></div>
			<div class = "small_devider"></div>
			<div style = "color: Black"> <strong><%= Account.find(report.account_id).first_name + " "+ Account.find(report.account_id).last_name%></strong></div>
			<div class = "small_devider"></div>
			on page: <%= report.page%> </br>
			<div class = "small_devider"></div>
			encountered: <%= report.issue%></br>
			<div class = "small_devider"></div>
			<hr>
			<div class = "small_devider"></div>
			<div class = "small_devider"></div>
			<%end%>
			<div>
			</div>

		</div>
	</div>
</div>
</div>
</div>

app/views/admin/stats.html.erb
<div class="container">
 <div id="blog" class="row"> 

  <div class="col-sm-2 paddingTop20">
   <%= render partial: "admin/side_bar"%>
    <div><h2 class="add"></h2></div>
  </div>
  <div class="col-md-10 blogShort">
<ul>
    
    

   
   		<div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading">Challenges</div>

      <!-- Table -->
	      <table class="table">
	        <thead>
	          <tr>
	            <th>#</th>
	            <th>Sender Email</th>
	            <th>Reciever Email</th>
	            <th>Time</th>
	            <th>Status</th>
	          </tr>
	        </thead>
	        <tbody>
	         <% Challenge.all.each do |challenge|%>
	          <tr>
	            <th scope="row"><%= challenge.id%></th>
	            <td><%= "#{Account.find(challenge.challenger_id).email} "%></td>
	            <td><%= challenge.get_challengee_email == nil ? "open" : challenge.get_challengee_email   %></td>
	            <td><% c = challenge.created_at.to_s(:long).split(" ") %> <%= "#{c[0]} #{c[1]} #{c[2]} "%></td>
	            <td> accepted </td>
	          </tr>
	          <%end %>
	        </tbody>
	      </table>
	    </div>
	  </div>
    
</ul>
  </div>

 <div class="col-md-12 gap10"></div>
</div>
</div>

app/views/admin/stats_debates.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

<div class = "admin_index_main">
<div class = "container">
<div class = "row"> 
	<div class = 'col-lg-2'>
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><%= link_to("Home", {:action => 'index'},)%></li>
			<li role="presentation"><%= link_to("Debates", {:action => 'debates'},)%></li>
			<li role="presentation"><%= link_to("Accounts", {:action => 'accounts'},)%></li>
			
			<li role="presentation" class="active"><%= link_to("Stats", {:action => 'stats'},)%></li>
			<% if current_account.privilege == 'super'%>
        <li role="presentation"><%= link_to("Reports", {:action => 'reports'})%></li>
        <li role="presentation"><a>Admins</a></li>
      <%end%>
  		</ul>

	</div>

	<div class = 'col-lg-10'>
		<div class = "row">
			<div class = "col-lg-12"><ul class="nav nav-tabs">
				  <li role="presentation" ><%= link_to("Home", {:action => 'stats'},)%></li>
				  <li role="presentation" ><%= link_to("Redirects", {:action => 'stats_redirects'},)%></li>
				  <li role="presentation" class="active"><%= link_to("Debates", {:action => 'stats_debates'},)%></li>
				  <li role="presentation"><%= link_to("Users", {:action => 'stats_users'},)%></li>
				</ul>
			</div>
			<div class = "col-lg-12 admin_stats_info_container">
				<div class = "row">
					<div class = "col-lg-12"></div>
					<div style = "margin-top: 10px; margin-botton: 10opx;" class = "col-lg-12">
						<div id="by_date" style="height: 250px;"></div>
					</div>
					<div class = "col-lg-12"> </div>
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div id="by_week" style="height: 250px;"></div>
					</div>
					<div class = "col-lg-12"> </div>
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div id="by_month" style="height: 250px;"></div>
					</div>
					<div class = "col-lg-12"> </div>
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div id="by_year" style="height: 250px;"></div>
					</div>
			</div>
		</div>
		</div>
	</div>
</div>
</div>
</div>
<script type="text/javascript">
	new Morris.Line({
	  // ID of the element in which to draw the chart.
	  element: 'myfirstchart',
	  // Chart data records -- each entry in this array corresponds to a point on
	  // the chart.
	  data: [
	    { year: '2008', value: 20 },
	    { year: '2009', value: 10 },
	    { year: '2010', value: 5 },
	    { year: '2011', value: 5 },
	    { year: '2012', value: 20 }
	  ],
	  // The name of the data record attribute that contains x-values.
	  xkey: 'year',
	  // A list of names of data record attributes that contain y-values.
	  ykeys: ['value'],
	  // Labels for the ykeys -- will be displayed when you hover over the
	  // chart.
	  labels: ['Value']
	});
</script>

app/views/admin/stats_redirects.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

<div class = "admin_index_main">
<div class = "container">
<div class = "row"> 
	<div class = 'col-lg-2'>
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><%= link_to("Visits", {:action => 'index'},)%></li>
			<li role="presentation"><%= link_to("Debates", {:action => 'debates'},)%></li>
			<li role="presentation"><%= link_to("Accounts", {:action => 'accounts'},)%></li>
		
			<li role="presentation" class="active"><%= link_to("Stats", {:action => 'stats'},)%></li>
			<% if current_account.privilege == 'super'%>
        <li role="presentation"><%= link_to("Reports", {:action => 'reports'})%></li>
        <li role="presentation"><a>Admins</a></li>
      <%end%>
  		</ul>

	</div>

	<div class = 'col-lg-10'>
		<div class = "row">
			<div class = "col-lg-12"><ul class="nav nav-tabs">
				  <li role="presentation" ><%= link_to("Home", {:action => 'stats'},)%></li>
				  <li role="presentation" class="active"><%= link_to("Redirects", {:action => 'stats_redirects'},)%></li>
				  <li role="presentation"><%= link_to("Debates", {:action => 'stats_debates'},)%></li>
				  <li role="presentation"><%= link_to("Users", {:action => 'stats_users'},)%></li>
				</ul>
			</div>
			<div class = "col-lg-12 admin_stats_info_container">
				<div class = "row">
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div class="alert alert-info" role="alert"><strong>Page Views Today:</strong> 18,547</div>

					</div>
					<div style = "margin-top: 10px; margin-bottom: 50px;" class = "col-lg-12">
						<div id="by_date" style="height: 250px;"></div>
					</div>
					<div style = "margin-top: 10px;" class = "col-lg-12"> 
						<div class="alert alert-info" role="alert"><strong>Page Views This Week:</strong> 18,547</div>

					</div>
					<div style = "margin-top: 10px; margin-bottom: 50px;" class = "col-lg-12">
						<div id="by_week" style="height: 250px;"></div>
					</div>
					<div style = "margin-top: 10px;" class = "col-lg-12"> 
						<div class="alert alert-info" role="alert"><strong>Page Views This Month:</strong> 18,547</div>

					</div>
					<div style = "margin-top: 10px; margin-bottom: 50px;" class = "col-lg-12">
						<div id="by_month" style="height: 250px;"></div>
					</div>
					<div style = "margin-top: 10px;" class = "col-lg-12"> 
						<div class="alert alert-info" role="alert"><strong>Page Views This Year:</strong> 18,547</div>

					</div>
					<div style = "margin-top: 10px; margin-bottom: 50px;" class = "col-lg-12">
						<div id="by_year" style="height: 250px;"></div>
					</div>
			</div>
		</div>
		</div>
	</div>
</div>
</div>
</div>
<script type="text/javascript">
	new Morris.Line({
	  // ID of the element in which to draw the chart.
	  element: 'by_date',
	  // Chart data records -- each entry in this array corresponds to a point on
	  // the chart.
	  data: [
	    { year: '2008', value: 20 },
	    { year: '2009', value: 10 },
	    { year: '2010', value: 5 },
	    { year: '2011', value: 5 },
	    { year: '2012', value: 20 }
	  ],
	  // The name of the data record attribute that contains x-values.
	  xkey: 'year',
	  // A list of names of data record attributes that contain y-values.
	  ykeys: ['value'],
	  // Labels for the ykeys -- will be displayed when you hover over the
	  // chart.
	  labels: ['Value']
	});

	new Morris.Line({
	  // ID of the element in which to draw the chart.
	  element: 'by_week',
	  // Chart data records -- each entry in this array corresponds to a point on
	  // the chart.
	  data: [
	    { year: '2008', value: 20 },
	    { year: '2009', value: 10 },
	    { year: '2010', value: 5 },
	    { year: '2011', value: 5 },
	    { year: '2012', value: 20 }
	  ],
	  // The name of the data record attribute that contains x-values.
	  xkey: 'year',
	  // A list of names of data record attributes that contain y-values.
	  ykeys: ['value'],
	  // Labels for the ykeys -- will be displayed when you hover over the
	  // chart.
	  labels: ['Value']
	});

	new Morris.Line({
	  // ID of the element in which to draw the chart.
	  element: 'by_month',
	  // Chart data records -- each entry in this array corresponds to a point on
	  // the chart.
	  data: [
	    { year: '2008', value: 20 },
	    { year: '2009', value: 10 },
	    { year: '2010', value: 5 },
	    { year: '2011', value: 5 },
	    { year: '2012', value: 20 }
	  ],
	  // The name of the data record attribute that contains x-values.
	  xkey: 'year',
	  // A list of names of data record attributes that contain y-values.
	  ykeys: ['value'],
	  // Labels for the ykeys -- will be displayed when you hover over the
	  // chart.
	  labels: ['Value']
	});

	new Morris.Line({
	  // ID of the element in which to draw the chart.
	  element: 'by_year',
	  // Chart data records -- each entry in this array corresponds to a point on
	  // the chart.
	  data: [
	    { year: '2008', value: 20 },
	    { year: '2009', value: 10 },
	    { year: '2010', value: 5 },
	    { year: '2011', value: 5 },
	    { year: '2012', value: 20 }
	  ],
	  // The name of the data record attribute that contains x-values.
	  xkey: 'year',
	  // A list of names of data record attributes that contain y-values.
	  ykeys: ['value'],
	  // Labels for the ykeys -- will be displayed when you hover over the
	  // chart.
	  labels: ['Value']
	});
</script>

app/views/admin/stats_users.html.erb
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

<div class = "admin_index_main">
<div class = "container">
<div class = "row"> 
	<div class = 'col-lg-2'>
		<ul class="nav nav-pills nav-stacked">
			<li role="presentation"><%= link_to("Home", {:action => 'index'},)%></li>
			<li role="presentation"><%= link_to("Debates", {:action => 'debates'},)%></li>
			<li role="presentation"><%= link_to("Accounts", {:action => 'accounts'},)%></li>
			
			<li role="presentation" class="active"><%= link_to("Stats", {:action => 'stats'},)%></li>
			<% if current_account.privilege == 'super'%>
        <li role="presentation"><%= link_to("Reports", {:action => 'reports'})%></li>
        <li role="presentation"><a>Admins</a></li>
      <%end%>
  		</ul>

	</div>

	<div class = 'col-lg-10'>
		<div class = "row">
			<div class = "col-lg-12"><ul class="nav nav-tabs">
				  <li role="presentation" ><%= link_to("Home", {:action => 'stats'},)%></li>
				  <li role="presentation" ><%= link_to("Redirects", {:action => 'stats_redirects'},)%></li>
				  <li role="presentation"><%= link_to("Debates", {:action => 'stats_debates'},)%></li>
				  <li role="presentation" class="active"><%= link_to("Users", {:action => 'stats_users'},)%></li>
				</ul>
			</div>
			<div class = "col-lg-12 admin_stats_info_container">
				<div class = "row">
					<div class = "col-lg-12"></div>
					<div style = "margin-top: 10px; margin-botton: 10opx;" class = "col-lg-12">
						<div id="by_date" style="height: 250px;"></div>
					</div>
					<div class = "col-lg-12"> </div>
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div id="by_week" style="height: 250px;"></div>
					</div>
					<div class = "col-lg-12"> </div>
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div id="by_month" style="height: 250px;"></div>
					</div>
					<div class = "col-lg-12"> </div>
					<div style = "margin-top: 10px;" class = "col-lg-12">
						<div id="by_year" style="height: 250px;"></div>
					</div>
			</div>
		</div>
		</div>
	</div>
</div>
</div>
</div>
<script type="text/javascript">
	new Morris.Line({
	  // ID of the element in which to draw the chart.
	  element: 'myfirstchart',
	  // Chart data records -- each entry in this array corresponds to a point on
	  // the chart.
	  data: [
	    { year: '2008', value: 20 },
	    { year: '2009', value: 10 },
	    { year: '2010', value: 5 },
	    { year: '2011', value: 5 },
	    { year: '2012', value: 20 }
	  ],
	  // The name of the data record attribute that contains x-values.
	  xkey: 'year',
	  // A list of names of data record attributes that contain y-values.
	  ykeys: ['value'],
	  // Labels for the ykeys -- will be displayed when you hover over the
	  // chart.
	  labels: ['Value']
	});
</script>

app/views/admin/topic_debates.html.erb
<div class="container">
 <div id="blog" class="row"> 

  <div class="col-sm-2 paddingTop20">
   <%= render partial: "admin/side_bar"%>
    <div><h2 class="add"></h2></div>
  </div>
  <div class="col-md-10 blogShort">
<ul>
    
    

    <% @topic.debates.each do |debate|%>
    <div class = "row">
      
      <p><h4><%= link_to debate.get_topic.topic_sentence, debate_path(debate)%></h4></p>
      <div class = "col-md-3">
        <%= link_to action: "debate_summary", id: debate.id do %>
            <span class = 'btn btn-primary btn-sm', style = "width: 90px;"> 
            <i class="fa fa-cog"></i> Summary 
            </span>
           <% end %>
           <div class = "small_devider"></div>
            <%= link_to debate_path(debate), method: :delete, remote: true , :class => 'btn btn-danger btn-sm', :style => "width: 90px;"  do %>
            <i class="fa fa-trash-o fa-sm"></i> Delete </a>
           <% end %>
      </div>
      
    </div>
    <%end %>
</ul>
  </div>

 <div class="col-md-12 gap10"></div>
</div>
</div>